---
default: true

# Allow long lines for now (badges, tables, code samples, generated diffs)
MD013: false

# Allow inline HTML (badges, embeds)
MD033: false

# Keep requirement that first line is a heading
MD041: true
---
