config:
  MD013: false   # long lines
  MD033: false   # inline HTML
  MD041: false   # first line must be a heading (disabled for badges)
  MD024:
    siblings_only: true  # duplicate headings allowed in different sections
