# Keep markdownlint focused and non-noisy for CI
# Docs: https://github.com/DavidAnson/markdownlint-cli2

config:
  # Long lines are common in tables/links; don’t fail CI on them
  MD013: false
  # Allow inline HTML snippets in docs/README
  MD033: false
  # Allow bare URLs (GitHub issues, PRs)
  MD034: false

ignores:
  - "node_modules/**"
  - ".venv*/**"
  - "dist/**"
  - "wheelhouse/**"
  - "build/**"
  - "bench/**"

# Limit linting to actual docs / repo text
globs:
  - "**/*.md"
  - "!node_modules/**"
  - "!.venv*/**"
