# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 The Vision Authors
minimum_pre_commit_version: "3.7.0"
exclude: |
  (?x)^(
    dist/|
    wheelhouse/|
    bench/out/|
    \.coverage|
    coverage\.xml|
    htmlcov/|
    \.venv/|
    venv/|
    \.mypy_cache/|
    \.ruff_cache/|
    __pycache__/|
    node_modules/
  )
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

