repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Markdownlint: same engine as CI, isolated Node env (no system Node needed).
  - repo: local
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        language: node
        entry: markdownlint-cli2-fix
        additional_dependencies:
          - markdownlint-cli2@^0.12.1
          - markdownlint@^0.33.0
        files: \.(md|markdown)$
        pass_filenames: true
