repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint (local)
        language: system
        entry: node_modules/.bin/markdownlint --config .markdownlint.jsonc --ignore-path .markdownlintignore
        files: \.md$
        pass_filenames: true
