[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "vision"
version = "0.0.2"
description = "vision package"
authors = [{name = "Vision Authors", email = "dev@example.com"}]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = ["opencv-python"]

[project.scripts]
vision = "vision.cli:main"
