# SPDX-License-Identifier: Apache-2.0
[detector]
model_path = "models/yolov8n.onnx"
input_size = 640

[tracker]
type = "bytetrack"

[embedder]
model = "ViT-B-32-openai"
batch_size = 8
device = "cpu"

[matcher]
index_type = "faiss-flat"
topk = 5
threshold = 0.35
min_neighbors = 1

[pipeline]
frame_stride = 1

[latency]
budget_ms = 66

[paths]
kb_json = "data/kb.json"
telemetry_csv = "artifacts/telemetry.csv"
