name: deprecated-ci-matrix
on:
  workflow_dispatch: {}
jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::warning::This workflow is deprecated. Use .github/workflows/verify.yml"
