# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 The Vision Authors
name: verify
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
  pull_request:
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          config: .markdownlint-cli2.yaml

  verify:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    name: verify (${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -r requirements-dev.txt
      - run: pip install -e .
      - run: make setup  # still ok; now it's a no-op if the above succeeded
      - name: Environment report
        run: |
          python -V
          python -m pip --version
          python - <<'PY'
from packaging import tags
print(f"platform tag: {next(tags.sys_tags())}")
PY
          python -m pip debug --verbose
      - run: make verify
      - run: PYTEST_ADDOPTS="-ra" make test-cov | tee pytest.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.python-version }}
          path: |
            .coverage
            coverage.xml
            htmlcov
            pytest.log
          if-no-files-found: ignore
      - run: python -m vision --version
      - run: vision --version
      - run: vision webcam --dry-run
      - run: vision webcam --use-fake-detector --dry-run

  package:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
      - run: python -m pip install --upgrade pip
      - run: python -m pip install build twine
      - run: python -m build
      - run: python -m twine check dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*
          if-no-files-found: error
