# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 The Vision Authors
name: verify
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
  pull_request:
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          config: .markdownlint-cli2.yaml

  verify:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    name: verify (${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -r requirements-dev.txt
      - run: pip install -e .
      - run: make setup  # still ok; now it's a no-op if the above succeeded
      - name: Environment report
        run: |
          python -V
          python -m pip --version
          python - <<'PY'
from packaging import tags
print(f"platform tag: {next(tags.sys_tags())}")
PY
          python -m pip debug --verbose
      - run: make verify
      - run: PYTEST_ADDOPTS="-ra" make test-cov | tee pytest.log
      - name: Fail on skips
        run: |
          python - <<'PY' > pytest-summary.txt
import re, pathlib
text = pathlib.Path('pytest.log').read_text()
line = ''
for l in text.splitlines():
    if re.search(r'==+ .* in .* seconds ==+', l):
        line = l
m = re.search(r'(skipped=\d+|\d+\s+skipped)', line or '')
skipped = 0
if m:
    skipped = int(re.search(r'\d+', m.group()).group())
print(f'skipped={skipped}')
exit(skipped != 0)
PY
          grep -q 'skipped=0' pytest-summary.txt
      - name: Show pytest tail on failure
        if: failure()
        run: |
          echo "::group::pytest tail"
          tail -n 200 pytest.log || true
          echo "::endgroup::"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.python-version }}
          path: |
            .coverage
            coverage.xml
            htmlcov
            pytest.log
          if-no-files-found: ignore
      - run: latvision --version
      - run: python -m vision --version
      - run: latvision webcam --dry-run
      - run: latvision webcam --use-fake-detector --dry-run
      - name: Ban runtime RIS
        run: scripts/check_no_runtime_ris.sh

  package:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
      - run: python -m pip install --upgrade pip
      - run: python -m pip install build twine
      - run: python -m build
      - run: python -m twine check dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*
          if-no-files-found: error
