name: rc-artifacts

on:
  push:
    tags:
      - "v0.1.0-rc*"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: pip }

      - name: Upgrade pip tooling
        run: python -m pip install -U pip setuptools wheel

      - name: Install (editable + dev + runtime)
        run: |
          pip install -e .
          pip install -r requirements-dev.txt
          pip install pillow numpy matplotlib

      - name: Build tiny fixture (best effort)
        run: |
          python scripts/build_fixture.py --seed 42 --out bench/fixture --n 400 || true

      - name: Run evaluator (best effort; guardrails relaxed)
        env:
          VISION_SILENCE_DEPRECATION: "1"
        run: |
          latvision eval --input bench/fixture --output bench/out --warmup 0 --unknown-rate-band 0.0,1.0 || true
          python scripts/print_summary.py --metrics bench/out/metrics.json || true

      - name: Check metrics.json shape (best effort)
        run: |
          if [ -f bench/out/metrics.json ]; then
            python - <<'PY'
import json
path = "bench/out/metrics.json"
required = ["sdk_version", "p95_ms", "slo_budget_ms", "slo_within_budget_pct"]
try:
    data = json.load(open(path))
    missing = [k for k in required if k not in data]
    if missing:
        print(f"::warning::metrics.json missing keys: {', '.join(missing)}")
except Exception as e:
    print(f"::warning::error parsing metrics.json: {e}")
PY
          else
            echo "::warning::bench/out/metrics.json missing"
          fi

      - name: Plot latency (best effort)
        run: |
          python scripts/plot_latency.py --input bench/out/stage_times.csv || true

      - name: Build wheels
        run: |
          python -m pip install build
          python -m build --wheel
          ls -la dist || true

      - uses: actions/upload-artifact@v4
        with:
          name: rc-artifacts
          path: |
            bench/out/metrics.json
            bench/out/stage_times.csv
            bench/out/latency.png
            dist/*.whl
          if-no-files-found: warn

