name: rc-artifacts
on:
  push:
    tags:
      - "v0.1.0-rc*"

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build
          pip install -e .
          pip install -r requirements-dev.txt
          pip install numpy pillow matplotlib
      - name: Import smoke (alias + legacy)
        run: |
          python - <<'PY'
          import pathlib
          import latency_vision as lv
          import vision as v
          print("lv_version:", lv.__version__)
          print("vision_path:", pathlib.Path(v.__file__).resolve())
          PY
      - name: Bench (offline)
        env:
          MPLBACKEND: Agg
        run: |
          python scripts/build_fixture.py --out bench/fixture --n 400
          latvision eval --input bench/fixture --output bench/out --budget-ms 33
          python scripts/print_summary.py --metrics bench/out/metrics.json
          python scripts/plot_latency.py --input bench/out/stage_timings.csv
      - name: Build wheels
        run: |
          python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rc-artifacts
          path: |
            bench/out/metrics.json
            bench/out/stage_timings.csv
            bench/out/latency.png
            dist/*.whl
          if-no-files-found: warn
